server:
  port: 8080
  error:
    whitelabel:
      enabled: false
spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  thymeleaf:
    cache: false
#    prefix: file:src/main/resources/templates/
#  web:
#    resources:
#      static-locations:
#        - classpath:/static/
#        - classpath:/public/
#        - classpath:/resources/
#        - classpath:/META-INF/resources/
  output:
    ansi:
      enabled: always


  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://ec2-18-224-143-16.us-east-2.compute.amazonaws.com:3306/vue_cdn_session_template
      username: dev
      password: 123123
      connection-timeout: 30000
      pool-name: HikariCP
      read-only: false
      connection-test-query: SELECT 'DEV'
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true  # JPQL ?? ??
    open-in-view: false

#logging.level:
#  org.hibernate.sql: debug
#  org.springframework.security: debug



